#define skip (10)
#define reverse (11)
#define drawTwo (12)
#define wildCard (13)
#define wildDrawFour (14)
#define notWild false
#define wild true
#define notSpecial false
#define special true
#define played true
#define notPlayed false
#define powerOn true
#define powerOff false
#define RED 'R'
#define GREEN 'G'
#define YELLOW 'Y'
#define BLUE 'B'
#define RED_TEXT     "\033[31m"
#define GREEN_TEXT   "\033[32m"
#define YELLOW_TEXT  "\033[33m"
#define BLUE_TEXT    "\033[34m"
#define PURPLE_TEXT "\033[35m"
#define ORANGE_TEXT "\033[38;5;208m"
#define RESET_TEXT   "\033[0m"
#define CLEAR_SCREEN "\033[2J\033[1;1H"
#define UNO (1)
#define WILD_COLOR 'W'
#define START 'S'
#define TERMINATE 'X'
#define userPlayer false
#define botPlayer true
#define DEV_MODE 'D'
bool devMode = false;
#define HUMAN (0)
#define STARTING_HAND_SIZE (7)
